#!/bin/bash

OUTPUT=README.md
TRAIN_SIZE=120
POSITIVE_RATE=10

while [ $POSITIVE_RATE -le 40 ]
do
    printf "\n\nEXECUTING SCRIPT WITH POSITIVE RATE = %d\n\n" "$POSITIVE_RATE"
    make OUTPUT=$OUTPUT POSITIVE_RATE=$POSITIVE_RATE
    POSITIVE_RATE=$[$POSITIVE_RATE+10]
done


