run: test2 test3 test4

test2:
	@echo 'Executing test2...'
	python3 cpeTest.py < input/input2.txt > output/output2.txt
	@echo 'Finished test2'

test3:
	@echo 'Executing test3...'
	python3 cpeTest.py < input/input3.txt > output/output3.txt
	@echo 'Finished test3'

test4:
	@echo 'Executing test4...'
	python3 cpeTest.py < input/input4.txt > output/output4.txt
	@echo 'Finished test4'
